server:
  port: 8080
  servlet:
    context-path: /blog

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/blog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #create update none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.orm.jdbc.bind: trace
