server:
  port: 80 # 기본적으로 스프링은 8080포트를 사용한다.
  servlet:
    context-path: /blog

spring:
  datasource:
    url: jdbc:mysql://aaadb.c7smw8oye3a4.ap-northeast-2.rds.amazonaws.com:3306/blog
    username: treesheep
    password: roffjrtl135


  jpa:
    hibernate:
      ddl-auto: create #create update none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace

###################################################


#server:
#  port: 8080 # 기본적으로 스프링은 8080포트를 사용한다.
#  servlet:
#    context-path: /blog
#
#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/blog
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  session:
#    store-type: jdbc
#    jdbc.initialize-schema: always
#
#  jpa:
#    hibernate:
#      ddl-auto: create #create update none
#    properties:
#      hibernate:
#        default_batch_fetch_size: 100
#        show-sql: true
#        format_sql: true
#        dialect: org.hibernate.dialect.H2Dialect
#
#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.orm.jdbc.bind: trace

